baseURL = "http://network2501.github.io/"
languageCode = "en-au"
title = "network2501"
theme = "accessible-minimalism"
summaryLength = 0
disableHugoGeneratorInject = true
enableRobotsTXT = true
[permalinks]
  posts = '/:year/:month/:title/'
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
