baseURL = "http://network2501.github.io/"
languageCode = "en-au"
title = "network2501"
theme = "accessible-minimalism"
disableHugoGeneratorInject = true
enableRobotsTXT = true
summaryLength = 0

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
